### PR TITLE
fix: add FAQ section

### PR DESCRIPTION
**Pull request by starlightknown**
image

### CODE REVIEW

**Comment by ashwinexe** [comment]
is this FAQ for ABCD workshop?

**Comment by starlightknown** [comment]
> is this FAQ for ABCD workshop?

Community

**Comment by ashwinexe** [comment]
@starlightknown got some conflicts in `index.html`

**Comment by starlightknown** [comment]
solved @ashwinexe

**Comment by ashwinexe** [comment]
@starlightknown 
image
I see this in netlify preview, can you confirm?

**Comment by starlightknown** [comment]
oh damnn, I didn't do the landing so looks like it got mixed up @ashwinexe unmerge this. Let me do it properly.

**Pull request merged**
